import Head from 'next/head';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import { withApollo } from '../utils/withApollo';

function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
      </Layout>
    </>
  )
}

export default withApollo({ ssr: false })(Home);
