import Head from 'next/head'
import { useRouter } from 'next/router'
import { useCookies } from 'react-cookie'
import { useLoginMutation } from '../generated/graphql'
import { useIsAuthNotRequired } from '../hooks/useIsAuthNotRequired'
import firebase from '../init/firebase'
import { withApollo } from '../utils/withApollo'

function Home() {
  const { query } = useRouter()

  const nextRoute = query.next ? query.next as string : '/feed'

  const { loading, refetch: refetchMeQuery, data } = useIsAuthNotRequired(nextRoute)
  const [login] = useLoginMutation()
  const [_, setTokenCookie] = useCookies(['token'])

  const handleLogin = async () => {
    try {
      const provider = new firebase.auth.GoogleAuthProvider();
      await firebase.auth().signInWithPopup(provider)
      const user = firebase.auth().currentUser;
      if (!user) {
        return
      }
      const idToken = await user.getIdToken()
      if (!idToken) {
        return
      }
      const response = await login({
        variables: {
          idToken,
          name: user.displayName || ''
        }
      })
      if (response.data?.login.errors) {
        console.error(response.data.login.errors)
      } else {
        setTokenCookie('token', response.data?.login.accessToken!, {
          maxAge: Date.now() + (1000 * 60 * 24 * 365) // 365 days
        })
        refetchMeQuery()
      }
    } catch (error) {
      console.error(error)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loading ?
          <div>
            Loading...
          </div>
          :
          (
            data?.user
              ? null :
              <main>
                <button onClick={handleLogin}>Login</button>
              </main>
          )
      }
    </div>
  )
}

export default withApollo({ ssr: false })(Home);
