import Head from 'next/head'
import { useCookies } from 'react-cookie'
import { MeDocument, useLoginMutation } from '../generated/graphql'
import { useIsAuthNotRequired } from '../hooks/useIsAuthNotRequired'
import firebase from '../init/firebase'
import styles from '../styles/Home.module.css'
import { withApollo } from '../utils/withApollo'

function Home() {
  const { loading } = useIsAuthNotRequired('/home', false)
  const [login] = useLoginMutation()
  const [_, setTokenCookie] = useCookies(['token'])

  const handleLogin = async () => {
    try {
      const provider = new firebase.auth.GoogleAuthProvider();
      await firebase.auth().signInWithPopup(provider)
      const user = firebase.auth().currentUser;
      if (!user) {
        return
      }
      const idToken = await user.getIdToken()
      if (!idToken) {
        return
      }
      const response = await login({
        variables: {
          idToken,
          name: user.displayName || ''
        },
        refetchQueries: [{ query: MeDocument }]
      })
      if (response.data?.login.errors) {
        console.error(response.data.login.errors)
      } else {
        setTokenCookie('token', response.data?.login.accessToken!)
        // localStorage.setItem('token', response.data?.login.accessToken!)
      }
    } catch (error) {
      console.error(error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        loading ?
          <div>
            Loading...
          </div>
          :
          <main className={styles.main}>
            <button onClick={handleLogin}>Login</button>
          </main>
      }
    </div>
  )
}

export default withApollo({ ssr: false })(Home);
